### ISSUE TITLE
`ArcIntern<T>`'s `Hash` implementation is invalid

### ISSUE THREAD

**Issue by ShadowJonathan** [ryzhyk/arc-interner#13]
Since `ArcIntern<T>` provides `Borrow<T>`, the Hash implementations have to be the same. However, they're not.

This caused some problems when coercing `ArcIntern` to `Borrow`, and `HashMaps` stopped working correctly, as the given hashmap (before the coercion) used `ArcIntern`'s hash functions, while after coercion, the hashmaps were looked up via `T`'s `Hash` via `Borrow<T>`, which caused wrong results.

**Comment by ryzhyk** [comment]
I agree.  We hash pointers instead of values as an optimization, but, as you point out, this is generally incorrect.

**Comment by ryzhyk** [comment]
@ShadowJonathan , can you confirm that #14 works for you?

**Comment by ShadowJonathan** [comment]
Yes, that works for me, thank you so much.
