### ISSUE TITLE
Consider using Arc::as_ptr

### ISSUE THREAD

**Issue by guswynn** [ryzhyk/arc-interner#7]
1.45 was stabilized: https://blog.rust-lang.org/2020/07/16/Rust-1.45.0.html
Which included `Arc::as_ptr`: https://doc.rust-lang.org/stable/std/sync/struct.Arc.html#method.as_ptr

I believe the use of this would remove the need for the unsafe line added in https://github.com/ryzhyk/arc-interner/pull/5

**Comment by ryzhyk** [comment]
Thanks for the heads up!  I released this as 0.5.0 to avoid breaking stuff for users of 0.4.
